version: '3.3'

services:
  svc:
    image: ${SNET_IMAGE}
    networks:
      - public
    volumes:
      - data:${SNET_DATA_MOUNTPOINT}
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        - traefik.enable=true
        - traefik.http.routers.${SNET_BASENAME}.rule=Host(`${SNET_HOSTNAME}`)
        - traefik.http.routers.${SNET_BASENAME}.entrypoints=${SNET_ENTRYPOINT}
        - traefik.http.routers.${SNET_BASENAME}.tls=true
        - traefik.http.routers.${SNET_BASENAME}.tls.certresolver=le
        - traefik.http.services.${SNET_BASENAME}.loadbalancer.server.port=${SNET_PORT}

networks:
  public:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/cdata/${SNET_BASENAME}
